import pyautogui

pyautogui.click(1777, 21, button=("left"))
pyautogui.sleep(1)

# Aqui é feita a inicialização do browser para que seja acessado o arquivo ao qual consiste a base de dados dos preços respectivos
# É feito também o download e acessado dentro da pasta "downloads" do Windows Explorer
pyautogui.press('win')
pyautogui.sleep(1)
pyautogui.write("Firefox")
pyautogui.sleep(2)
pyautogui.press('enter')
pyautogui.sleep(10)
pyautogui.write("https://docs.google.com/spreadsheets/d/1vx1vcvRx9dAjXYaDWgBPc1UGV4RABIuT52Nxq4RRPNc/edit#gid=490033407")
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(6)
pyautogui.click(109, 196, button='left')
pyautogui.sleep(1)
pyautogui.click(292, 508, button='left')
pyautogui.sleep(1)
pyautogui.click(651, 510, button='left')
pyautogui.sleep(10)
pyautogui.hotkey('alt', 'F4')
# Aqui o browser Firefox estará sendo encerrado

# Aqui estará sendo aberto o explorador de arquivos para que seja encontrado o arquivo excel baixado
pyautogui.hotkey('win', 'e')
pyautogui.sleep(6)


# Aqui a execução estará colocando a janela e uma posição padrão (full screen) para que seja continuada a execução com os campos certos.
pyautogui.hotkey('win', 'up')
pyautogui.sleep(1)
pyautogui.hotkey('win', 'up')
pyautogui.sleep(1)
pyautogui.click(982, 20, button='left')
pyautogui.sleep(1)
pyautogui.hotkey('win', 'down')
pyautogui.sleep(1)
pyautogui.hotkey('win', 'up')
pyautogui.sleep(1)
# Finalizando aqui...

# Aqui, o comando estará a procura do arquivo em um local previamente determinado e padronizado por ser um download e também o abrindo.
pyautogui.click(123, 401, button='left')
pyautogui.sleep(1)
pyautogui.click(503, 261, button='left')
pyautogui.click(503, 261, button='left')
pyautogui.sleep(10)

# Aqui a execução estará colocando a janela e uma posição padrão (full screen) para que seja continuada a execução com os campos certos.
pyautogui.hotkey('win', 'up')
pyautogui.sleep(1)
pyautogui.hotkey('win', 'up')
pyautogui.sleep(1)
pyautogui.click(614, 16, button='left')
pyautogui.sleep(1)
pyautogui.hotkey('win', 'down')
pyautogui.sleep(1)
pyautogui.hotkey('win', 'up')
pyautogui.sleep(1)
# Finalizando aqui...

# Neste comando, estaremos fechando o Windows Explorer que havia sido aberto anteriormente mas que agora não haverá mais utilidade pois o arquivo já foi encontrado e aberto
pyautogui.hotkey('alt', 'tab')
pyautogui.sleep(1)
pyautogui.hotkey('alt', 'f4')
pyautogui.sleep(1)

# Já com o arquivo aberto, aqui está sendo filtrado e mesclado as informações de três colunas em apenas uma para que posteriormente esta unificada seja a base da função "=PROCV()"
pyautogui.click(1477, 100, button='left')
pyautogui.sleep(6)
pyautogui.click(121, 315, button='left')
pyautogui.sleep(1)
pyautogui.write("=B2&C2&D2")
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.click(121, 315, button='left')
pyautogui.sleep(1)
pyautogui.click(205, 327, button='left')
pyautogui.click(205, 327, button='left')

# Aqui, a execucução estará convertento as fórumulas em valores para a leitura da funçaõ que será aplicada posteriormente
pyautogui.sleep(1)
pyautogui.click(119, 267, button='left')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'c')
pyautogui.sleep(1)
pyautogui.click(119, 267, button='right')
pyautogui.sleep(1)
pyautogui.click(223, 400, button='left')

# Aqui o comando estará excluindo as colunas com informações duplicadas e portanto desnecessárias para o nosso "=PROCV" funcionar.
pyautogui.sleep(1)
pyautogui.click(291, 268, button='right')
pyautogui.sleep(1)
pyautogui.click(402, 518, button='left')

pyautogui.sleep(1)
pyautogui.click(291, 268, button='right')
pyautogui.sleep(1)
pyautogui.click(402, 518, button='left')

pyautogui.sleep(1)
pyautogui.click(291, 268, button='right')
pyautogui.sleep(1)
pyautogui.click(402, 518, button='left')
pyautogui.sleep(1)

# Agora, estaremos abrindo espaço com uma divisão de telas para que possamos importar os dados de uma planilha para outra
pyautogui.hotkey('win', 'left')
pyautogui.sleep(1)
pyautogui.click(303, 21, button='left')
pyautogui.sleep(1)
pyautogui.click(1853, 58, button='left')
pyautogui.click(1853, 58, button='left')
pyautogui.sleep(10)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.hotkey('win', 'right')
pyautogui.sleep(2)
pyautogui.click(1250, 20, button='left')
pyautogui.sleep(1)

# Já com os dois arquivos abertos, estaremos começando a importação
pyautogui.click(1880, 1007, button='left')
pyautogui.sleep(1)
pyautogui.click(1725, 500, button='left')
pyautogui.sleep(1)
pyautogui.click(1761, 673, button='left')
pyautogui.sleep(1)
pyautogui.click(1192, 291, button='left')
pyautogui.write("=")
pyautogui.sleep(1)
pyautogui.click(17, 264, button='left')
pyautogui.sleep(1)
pyautogui.click(17, 264, button='left')
pyautogui.click(17, 264, button='left')
pyautogui.sleep(1)
pyautogui.click(1851, 229, button='left')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'a')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'x')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'u')
pyautogui.sleep(1)
pyautogui.write('XXX-XXX')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'v')
pyautogui.sleep(1)
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.press("del")
pyautogui.sleep(1)
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("enter")
pyautogui.sleep(3)
pyautogui.press("enter")
pyautogui.sleep(2)
pyautogui.click(1880, 437, button='left')
pyautogui.sleep(2)

# Já com os dados importados para a planilha principal, estaremos fechando a base de dados primária e maximixando a janela do arquivo principal
pyautogui.click(934, 20, button='left')
pyautogui.sleep(3)
pyautogui.press("tab")
pyautogui.sleep(1)
pyautogui.press("enter")
pyautogui.sleep(2)
pyautogui.click(1235, 21, button='left')

# Aqui a execução estará colocando a janela e uma posição padrão (full screen) para que seja continuada a execução com os campos certos.
pyautogui.hotkey('win', 'up')
pyautogui.sleep(2)
pyautogui.click(1235, 21, button='left')
pyautogui.sleep(1)
pyautogui.hotkey('win', 'up')
pyautogui.sleep(1)
pyautogui.click(614, 16, button='left')
pyautogui.sleep(1)
pyautogui.hotkey('win', 'down')
pyautogui.sleep(1)
pyautogui.hotkey('win', 'up')
pyautogui.sleep(1)
# Finalizando aqui...

# Agora estaremos formatando toda a planilha para que seja corredamente analisada como relatório.
pyautogui.click(17, 265, button='left')
pyautogui.sleep(1)
pyautogui.hotkey('ctrl', 'c')
pyautogui.sleep(1)
pyautogui.click(17, 265, button='right')
pyautogui.sleep(1)
pyautogui.click(118, 400, button='left')
pyautogui.sleep(1)
# (acima foi formatado os valores de toda a planilha)

pyautogui.click(1892, 1007, button='left')
pyautogui.sleep(1)
pyautogui.click(876, 618, button='left')
pyautogui.click(876, 618, button='left')
pyautogui.write("40")
pyautogui.press("enter")
pyautogui.sleep(3)
pyautogui.hotkey("ctrl", "up")
pyautogui.hotkey("ctrl", "up")
pyautogui.hotkey("ctrl", "up")
pyautogui.hotkey("ctrl", "up")
pyautogui.hotkey("ctrl", "up")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.hotkey("ctrl", "left")
pyautogui.sleep(2)
# (acima foi configurado o campo de visão para melhor ambiente de trabalho)

# Aqui, está sendo selecionado um campo ao qual faremos alterações
pyautogui.click(193, 280, button='left')
pyautogui.sleep(1)
pyautogui.keyDown('shift')
pyautogui.click(1599, 607)
pyautogui.keyUp('shift')
pyautogui.sleep(1)

# Aqui estaremos abrindo o menu de substituições para as fazermos
pyautogui.hotkey('ctrl', 'u')
pyautogui.sleep(1)
pyautogui.hotkey('shift', 'tab')
pyautogui.sleep(1)
pyautogui.write(" ")
pyautogui.sleep(1)
pyautogui.press("tab")
pyautogui.sleep(1)
pyautogui.press("del")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("enter")
pyautogui.sleep(2)
pyautogui.press("enter")

pyautogui.sleep(1)
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.write(".")
pyautogui.sleep(1)
pyautogui.press("tab")
pyautogui.write(",")
pyautogui.sleep(1)
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("enter")
pyautogui.sleep(2)
pyautogui.press("enter")

pyautogui.sleep(1)
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.sleep(1)
pyautogui.write("S,Cadastro")
pyautogui.sleep(1)
pyautogui.press("tab")
pyautogui.write("S. Cadastro")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("enter")
pyautogui.sleep(2)
pyautogui.press("enter")
pyautogui.sleep(2)

pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.press("enter")

pyautogui.sleep(1)
pyautogui.click(145, 975, button='left')
pyautogui.sleep(1)
pyautogui.click(843, 321, button='left')
pyautogui.sleep(1)
pyautogui.write("=A1")
pyautogui.sleep(1)
pyautogui.press("enter")
pyautogui.sleep(1)
pyautogui.press("up")
pyautogui.sleep(1)
pyautogui.hotkey("ctrl", "c")
pyautogui.sleep(1)
pyautogui.click(840, 320, button='right')
pyautogui.sleep(1)
pyautogui.click(939, 451, button='left')
pyautogui.sleep(1)
pyautogui.click(34, 281, button='left')
pyautogui.sleep(1)
pyautogui.click(204, 975, button='left')
pyautogui.sleep(1)
pyautogui.click(27, 269, button='left')